@server = http://localhost
@port = 3000
@url = {{server}}:{{port}}

###############################################

// Test: Get blablabla
// Expected HTTP response status code: 200
// Expected response: an object (json) with an array with all courses (including subject for each course)
// [{}, {}, ...]
GET {{url}}/testing

###############################################

// Test: Get question by id
// Expected HTTP response status code: 200
// Expected response:
# {
#   "_id": "63ad827e9d82971b6593a00f",
#   "creator": "Admin",
#   "name": "Swedish question #1",
#   "question": "Vad heter Sveriges huvudstad?",
#   ...
GET {{url}}/questions/63ad827e9d82971b6593a00f

###############################################

// Test: Add question
// Expected HTTP response status code: 200
// Expected response:
# {
#   "creator": "63af18d1fb461af8dc235cc6",
#   "name": "test",
#   "question": "test",
#   "option1": "test",
#   ...
POST {{url}}/questions HTTP/1.1
Content-Type: application/json

{
  "creator": "63af18d1fb461af8dc235cc6",
  "name": "test",
  "question": "test",
  "option1": "test",
  "optionX": "test",
  "option2": "test",
  "correctOption": "test",
  "level": 1,
  "subject": ["63aee215b2c2038cfd5bd853"],
  "language": "test"
}

###############################################

// Test: Update question
// Expected HTTP response status code: 202
// 
PUT {{url}}/questions/63ad827e9d8291b6593a00f HTTP/1.1
Content-Type: application/json

{
  "creator": "63af18d1fb461af8dc235cc6",
  "name": "test",
  "question": "testa",
  "option1": "test",
  "optionX": "test",
  "option2": "test",
  "correctOption": "test",
  "level": 1,
  "subject": ["63aee215b2c2038cfd5bd853"],
  "language": "test"
}

###############################################

// Test: Delete the test question
// Expected HTTP response status code: 200 OR 404
// Expected response: an object (json) with a questions
#   ...
#   "creator": "test",
#   "name": "test",
#   "question": "test",
#   "option1": "test",
#   ...
DELETE {{url}}/questions/test

###############################################